M48
; DRILL file {KiCad (6.0.0-rc1-120-ge56e61ffb5)} date Sat Jan  8 17:42:39 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-01-08T17:42:39+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0-rc1-120-ge56e61ffb5)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0433
%
G90
G05
T1
X4.47Y-3.505
X4.47Y-3.605
T0
M30
